FROM node:15-alpine

RUN ["npm", "install", "-g", "npm@latest"]

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN ["chmod", "+x", "/wait"]

WORKDIR /usr/src/app
COPY package* ./
RUN ["npm", "ci"]

EXPOSE 8000
CMD /wait && npm run migrate -- up && npm run dev
